#!/usr/bin/env bash
#dding the file to listen to the port
sudo apt-get update
sudo apt-get install nginx -y
sudo systemctl start nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo systemctl restart nginx
