#!/usr/bin/env bash
#dding the file to listen to the port
sudo apt-get update
sudo apt-get install nginx -y
echo "Holberton School for the win!" | sudo tee /var/www/html/index.nginx-debian.html
sudo systemctl restart nginx
