#!/usr/bin/env bash
#dding the file to listen to the port
sudo apt-get update -y
sudo apt-get install nginx -y
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo sed -i "38i \tlocation /redirect_me {\n\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4\n" /etc/nginx/sites-available/default
sudo service nginx start
