#!/usr/bin/env bash
#dding the file to listen to the port
sudo apt-get update -y
sudo apt install haproxy=1.6.\* -y
echo "frontend 766-lb-01
        bind *:80
        default_backend 766-backend
backend 766-backend
        balance roundrobin
        server web1 35.227.47.184:80 check
        server web2 35.190.188.208:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
