#!/usr/bin/env bash
#dding the file to listen to the port
sudo apt-get update -y
sudo apt install haproxy=1.6.\* -y
echo "frontend 766-lb-01
        bind *:80
        default_backend 766-backend
backend 766-backend
        balance roundrobin
        server 766-web-01 35.231.255.39:80 check
        server 766-web-02 35.196.178.86:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
