#!/usr/bin/env bash
# holi this is a file for display the PID
function control_c {
    echo "I am invincible!!!"
} 
trap control_c SIGTERM
while [ 1 ]
do
    echo "To infinity and beyond"
    sleep 2
done
