#!/usr/bin/env bash
# while loop + IFS.
while IFS=: read -r USER PASS USER_ID GROUP_ID USER_ID_INFO HOME_DIR SHELL
do
    echo "The user $USER is part of the $GROUP_ID gang, lives in $HOME_DIR and rides $SHELL. $USER_ID's place is protected by the passcode $PASS, more info about the user here: $USER_ID_INFO"
done < /etc/passwd