#!/usr/bin/env bash
# continue until $n equals 10
n=1
while [ $n -le 10 ]
do
    if [ $n -ne 9 ]
    then
	    echo "Holberton School"
    else
        echo "Hi"
    fi
	n=$(( n+1 ))	 # increments $n
done
