#!/usr/bin/env bash
# continue until $n equals 10
n=1

while [ $n -le 10 ]
do
    if [ $n -eq 4 ]
    then
        echo "bad luck"
    elif [ $n -eq 8 ]
    then
        echo "good luck"
    else
        echo "Holberton School"
    fi
	n=$(( n+1 ))	 # increments $n
done