#!/usr/bin/env bash
# continue until $n equals 10
h=0
while [ $h -le 12 ]
do
	echo "Hour: $h"
    m=1
    while [ $m -le 59 ]
    do
        echo "$m"
        m=$(( m+1 ))	 # increments $m
    done
    h=$(( h+1 ))	 # increments $m
done